### ISSUE TITLE
Plugin Usage

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [FlorianPallas/advanced-flashcards#1]
Brother, let me introduce how to use it. I can't use it.

**Comment by FlorianPallas** [comment]
This plugin is still under heavy development and barely documented. Not ready for production use cases.

If you do not need the collaborative features this plugin provides (supporting flashcards with multiple users in one vault) there are better supported alternatives out there already ([see here](https://obsidian.md/plugins?search=anki)).

**Comment by shoudeyunkaijianyueming** [comment]
Hope to develop it quickly, come on！
